version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: node.dockerfile
    image: bmarete/gallery:1.0
    container_name: gallery-app
    ports:
      - '8000:8000'
    env_file:
      - './.env'
    networks:
      - my_network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - database:/data/db
    networks:
      - my_network

volumes:
  database:

networks:
  my_network:
    driver: bridge
